dependencies:
  build:
    - ruby:2.6.3

build_targets:
  - name: default
    commands:
      - gem install bundler
      - bundle install
    tags:
     channel: experimental
ci:
  builds:
    - name: default
      build_target: default